name: collegenius
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ^3.1.0

dependencies:
  connectivity_plus: ^4.0.2
  course_select_api:
    path: packages/course_select_api
  eeclass_api:
    path: packages/eeclass_api
  equatable: ^2.0.3
  firebase_analytics: ^10.4.5
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.3.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_downloader: ^1.8.1
  flutter_inappwebview: ^5.4.3+7
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  formz: ^0.6.0
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.4.0
  mockito: ^5.3.0
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  portal_api:
    path: packages/portal_api
  school_events_api:
    path: packages/school_events_api
  test: ">=1.0.0 <2.0.0"
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.1.4

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: images/collegenius_ios.png
  adaptive_icon_background: "images/collegenius_back.png"
  adaptive_icon_foreground: "images/collegenius_fore.png"
# For events on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  assets:
    - images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSansTC-Regular.otf
        - asset: fonts/NotoSansTC-Bold.otf
        - asset: fonts/NotoSansTC-Light.otf
        - asset: fonts/NotoSansTC-Black.otf
        - asset: fonts/NotoSansTC-Medium.otf
        - asset: fonts/NotoSansTC-Thin.otf
  uses-material-design: true
