// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-XwdZfHpd4MG8xpvodq8LQK5xOKvbx80',
    appId: '1:818341360067:web:2d3872a8a36076ac38cd76',
    messagingSenderId: '818341360067',
    projectId: 'collegenius-99f34',
    authDomain: 'collegenius-99f34.firebaseapp.com',
    storageBucket: 'collegenius-99f34.appspot.com',
    measurementId: 'G-LXFPGLE3CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0cn5cLcQa6vW8yV8V61JSTej_hAgEzRo',
    appId: '1:818341360067:android:c11cd973987dec1638cd76',
    messagingSenderId: '818341360067',
    projectId: 'collegenius-99f34',
    storageBucket: 'collegenius-99f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD46e3btv8hIJu6qtOvGUCY1aRwaxJmonc',
    appId: '1:818341360067:ios:963986e46b471f7c38cd76',
    messagingSenderId: '818341360067',
    projectId: 'collegenius-99f34',
    storageBucket: 'collegenius-99f34.appspot.com',
    iosClientId: '818341360067-249te3ik6aqm7vmj99p9fil6htskvhq5.apps.googleusercontent.com',
    iosBundleId: 'com.dimlee.collegenius',
  );
}
