name: school_events_api
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  dio: ^4.0.4
  html: ^0.15.0
  json_annotation: ^4.4.0
dev_dependencies:

  build_runner: ^2.1.7
  json_serializable: ^6.1.4
